title: Ben Blumer
description: Robotics Engineer
site_title: 'Ben Blumer'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: BnjBlm
# blog_url: https://www.nagekar.com
email: benjaminaaronblumer@gmail.com
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: G-LQXVD5E1G1

